/* Generated By:JavaCC: Do not edit this line. AimConstants.java */
package trollAim;

public interface AimConstants {

  int EOF = 0;
  int ADDEQ = 6;
  int ADDSYM = 7;
  int CHANGESYM = 8;
  int BOTTOM = 9;
  int COEFFICIENT = 10;
  int DATA = 11;
  int DATATYPE = 12;
  int DTRM = 13;
  int ENDOGENOUS = 14;
  int EQTYPE = 15;
  int EXOGENOUS = 16;
  int FILEMOD = 17;
  int IMPOSED = 18;
  int INNOV = 19;
  int NOTD = 20;
  int STOCH = 21;
  int TOP = 22;
  int USEMOD = 23;
  int PLUS = 24;
  int MINUS = 25;
  int MULTIPLY = 26;
  int DIVIDE = 27;
  int EXP = 28;
  int FLOAT = 29;
  int FLOATBASE = 30;
  int INTEGER = 31;
  int DIGIT = 32;
  int IDENTIFIER = 33;
  int LETTER = 34;
  int COMMA = 35;
  int PERIOD = 36;
  int COLON = 37;
  int SEMICOLON = 38;
  int EQUALS = 39;
  int OPENPAREN = 40;
  int CLOSEPAREN = 41;
  int COMMENT = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\">>\"",
    "<ADDEQ>",
    "<ADDSYM>",
    "<CHANGESYM>",
    "<BOTTOM>",
    "<COEFFICIENT>",
    "<DATA>",
    "<DATATYPE>",
    "<DTRM>",
    "<ENDOGENOUS>",
    "<EQTYPE>",
    "<EXOGENOUS>",
    "<FILEMOD>",
    "<IMPOSED>",
    "<INNOV>",
    "<NOTD>",
    "<STOCH>",
    "<TOP>",
    "<USEMOD>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "<FLOAT>",
    "<FLOATBASE>",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"//\"",
  };

}
