/* Generated By:JavaCC: Do not edit this line. AimConstants.java */
package trollAim;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AimConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADDEQ = 6;
  /** RegularExpression Id. */
  int ADDSYM = 7;
  /** RegularExpression Id. */
  int CHANGESYM = 8;
  /** RegularExpression Id. */
  int BOTTOM = 9;
  /** RegularExpression Id. */
  int COEFFICIENT = 10;
  /** RegularExpression Id. */
  int DATA = 11;
  /** RegularExpression Id. */
  int DATATYPE = 12;
  /** RegularExpression Id. */
  int DTRM = 13;
  /** RegularExpression Id. */
  int ENDOGENOUS = 14;
  /** RegularExpression Id. */
  int EQTYPE = 15;
  /** RegularExpression Id. */
  int EXOGENOUS = 16;
  /** RegularExpression Id. */
  int FILEMOD = 17;
  /** RegularExpression Id. */
  int IMPOSED = 18;
  /** RegularExpression Id. */
  int INNOV = 19;
  /** RegularExpression Id. */
  int NOTD = 20;
  /** RegularExpression Id. */
  int STOCH = 21;
  /** RegularExpression Id. */
  int TOP = 22;
  /** RegularExpression Id. */
  int USEMOD = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULTIPLY = 26;
  /** RegularExpression Id. */
  int DIVIDE = 27;
  /** RegularExpression Id. */
  int EXP = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int FLOATBASE = 30;
  /** RegularExpression Id. */
  int INTEGER = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int PERIOD = 36;
  /** RegularExpression Id. */
  int COLON = 37;
  /** RegularExpression Id. */
  int SEMICOLON = 38;
  /** RegularExpression Id. */
  int EQUALS = 39;
  /** RegularExpression Id. */
  int OPENPAREN = 40;
  /** RegularExpression Id. */
  int CLOSEPAREN = 41;
  /** RegularExpression Id. */
  int COMMENT = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\">>\"",
    "<ADDEQ>",
    "<ADDSYM>",
    "<CHANGESYM>",
    "<BOTTOM>",
    "<COEFFICIENT>",
    "<DATA>",
    "<DATATYPE>",
    "<DTRM>",
    "<ENDOGENOUS>",
    "<EQTYPE>",
    "<EXOGENOUS>",
    "<FILEMOD>",
    "<IMPOSED>",
    "<INNOV>",
    "<NOTD>",
    "<STOCH>",
    "<TOP>",
    "<USEMOD>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "<FLOAT>",
    "<FLOATBASE>",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"//\"",
  };

}
